"""Render brain.db -> vault/auto/*.md — the Obsidian-readable live-numbers layer.

Deterministic, regenerated from SQL, NEVER hand-edited and NEVER LLM-written
(same rule as BRAIN_SUMMARY.md): the vault's curated notes are the narrative
layer; this module is the only writer of vault/auto/. Wikilinks tie methods to
lessons so Obsidian's graph shows the real relationships. Owner (2026-07-06):
"t muốn dùng obsidian cho m, để nắm context tốt hơn".
"""
from __future__ import annotations

from pathlib import Path

import brain

ROOT = Path(__file__).resolve().parent
AUTO = ROOT / "vault" / "auto"
_HDR = "> ⚙️ AUTO-RENDERED from brain.db — do not edit (regenerated by brain_vault.render_auto)\n\n"


def _w(name: str, body: str) -> None:
    AUTO.mkdir(parents=True, exist_ok=True)
    (AUTO / name).write_text(_HDR + body + "\n", encoding="utf-8")


def render_auto() -> None:
    if not brain.DB.exists():
        return
    con = brain.connect(readonly=True)
    try:
        c = brain.trial_counts()

        # armed.md
        rows = list(con.execute(
            "SELECT method_id, state, reason, valid_at FROM method_state WHERE invalid_at IS NULL"))
        body = f"# Armed methods\n\ntrials={c['total']} · distinct={c['distinct_methods']}\n\n"
        for r in rows:
            body += f"- **[[auto/methods/{r['method_id']}|{r['method_id']}]]** — {r['state']} từ {r['valid_at']} ({r['reason']})\n"
        _w("armed.md", body or "# Armed methods\n(none)")

        # lessons.md
        body = "# Lessons (3 bậc: candidate → advisory → active)\n\n" \
               "| lesson | status | n | eff_n | mission_n | avg_r | label |\n|---|---|---|---|---|---|---|\n"
        for r in con.execute("SELECT * FROM lessons ORDER BY CASE status WHEN 'active' THEN 0 "
                             "WHEN 'advisory' THEN 1 ELSE 2 END, lesson_id"):
            body += (f"| {r['lesson_id']} | **{r['status']}** | {r['n']} | {r['eff_n']} | "
                     f"{r['mission_n']} | {r['avg_r']} | {r['label']} |\n")
        _w("lessons.md", body)

        # graveyard.md (top by evidence)
        body = "# Graveyard — idea đã CHẾT (novelty gate chặn re-test)\n\n" \
               "| method | failure | side | oosN | meanR | p | source |\n|---|---|---|---|---|---|---|\n"
        for r in con.execute(
                "SELECT method_id, failure_mode, side, oos_n, oos_mean_r, pvalue, source FROM trials "
                "WHERE verdict='DEAD' ORDER BY COALESCE(oos_n,0) DESC LIMIT 60"):
            body += (f"| {r['method_id']} | {r['failure_mode']} | {r['side']} | {r['oos_n']} | "
                     f"{r['oos_mean_r']} | {r['pvalue']} | {r['source']} |\n")
        _w("graveyard.md", body)

        # trials-stats.md
        body = f"# Trial registry (DSR ledger)\n\n- total trials: **{c['total']}**\n" \
               f"- distinct methods: **{c['distinct_methods']}**\n\n| source | n | dead |\n|---|---|---|\n"
        for r in con.execute("SELECT source, COUNT(*) n, SUM(verdict='DEAD') d FROM trials GROUP BY source"):
            body += f"| {r['source']} | {r['n']} | {r['d']} |\n"
        _w("trials-stats.md", body)

        # per-armed method note (deep dive + wikilinks to lessons)
        (AUTO / "methods").mkdir(parents=True, exist_ok=True)
        for r in rows:
            mid = r["method_id"]
            t = con.execute("SELECT * FROM trials WHERE method_id=? ORDER BY created_at DESC LIMIT 5",
                            (mid,)).fetchall()
            b = f"# {mid}\n\nstate: **{r['state']}** (từ {r['valid_at']})\n\n## 5 trial gần nhất\n" \
                "| when | source | verdict | oosN | meanR | p | lockbox p |\n|---|---|---|---|---|---|---|\n"
            for x in t:
                b += (f"| {x['created_at']} | {x['source']} | {x['verdict']} | {x['oos_n']} | "
                      f"{x['oos_mean_r']} | {x['pvalue']} | {x['lockbox_pvalue']} |\n")
            a = con.execute(
                "SELECT COUNT(*) n, SUM(net>0) w, AVG(r) ar FROM trade_autopsy WHERE method_id=?",
                (mid,)).fetchone()
            b += (f"\n## Autopsy\nn={a['n']} wins={a['w']} avgR={round(a['ar'], 3) if a['ar'] is not None else None}\n"
                  f"\nLiên quan: [[auto/lessons]] · [[validation-pipeline]] · [[sizing]]\n")
            (AUTO / "methods" / f"{mid}.md").write_text(_HDR + b, encoding="utf-8")
    finally:
        con.close()


if __name__ == "__main__":
    render_auto()
    print("vault/auto rendered")
